/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/headinspace/head.glb");

  return (
    <group {...props} scale={1.3} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube001.geometry}>
        <meshStandardMaterial />
      </mesh>
    </group>
  );
}

useGLTF.preload("/headinspace/head.glb");
